from pathlib import Path
import math, json, html
import fitz
P=Path(__file__).resolve().parent
# Exact vector diagrams; no raster image generation. The large structure is an original teaching example.
def line(x1,y1,x2,y2,color='#223344',width=2.6):
 return f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{color}" stroke-width="{width}" stroke-linecap="round"/>'
def txt(x,y,t,color='#223344',size=19):
 return f'<text x="{x}" y="{y}" fill="{color}" font-family="Arial,sans-serif" font-size="{size}" text-anchor="middle">{t}</text>'
def molecule(large=False,product=False,cue=True):
 bg='#adb5c0' if cue else '#223344'; active='#223344'; blue='#1765b0'; red='#c43a40'
 s=''
 if large:
  # para-substituted benzene: cyclohexyl at left, three CH2 and terminal CHO at right.
  pts=[(170+48*math.cos(math.radians(a)),130+48*math.sin(math.radians(a))) for a in [0,60,120,180,240,300]]
  for i in range(6): s+=line(*pts[i],*pts[(i+1)%6],bg)
  for i in [0,2,4]:
   a,b=pts[i],pts[(i+1)%6]; a=(170+(a[0]-170)*.79,130+(a[1]-130)*.79);b=(170+(b[0]-170)*.79,130+(b[1]-130)*.79);s+=line(*a,*b,bg,2)
  pts2=[(43+32*math.cos(math.radians(a)),130+32*math.sin(math.radians(a))) for a in [0,60,120,180,240,300]]
  for i in range(6):s+=line(*pts2[i],*pts2[(i+1)%6],bg)
  s+=line(75,130,122,130,bg)
  chain=[(218,130),(250,110),(282,130),(314,110),(346,130)]
  for a,b in zip(chain,chain[1:]):s+=line(*a,*b,bg)
  cx,cy=346,130
 else:
  s+=line(125,145,180,113,bg);cx,cy=180,113
 if cue: s+=f'<rect x="{cx-15}" y="{cy-66}" width="90" height="110" rx="16" fill="none" stroke="#178477" stroke-width="1.6" stroke-dasharray="5 4"/>'
 if product:
  s+=line(cx,cy,cx+38,cy-23,active)+txt(cx+56,cy-25,'OH',active)
 else:
  s+=line(cx-3,cy-3,cx-3,cy-39,active)+line(cx+3,cy-3,cx+3,cy-39,active)
  s+=txt(cx,cy-46,'O',red if cue else active)
  s+=line(cx,cy,cx+31,cy+18,active)+txt(cx+44,cy+28,'H',active)
  if cue:s+=f'<circle cx="{cx}" cy="{cy}" r="4" fill="{blue}"/>'
 return s

def reaction(large=False,cue=True):
 left=molecule(large,False,cue);right=molecule(large,True,cue)
 return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 255" role="img" aria-label="{'Large aldehyde' if large else 'Ethanal'} reacts with sodium borohydride in methanol to form a primary alcohol"><rect width="1000" height="255" fill="white"/>{left}<g transform="translate(570 0)">{right}</g>{line(435,130,548,130)}<path d="M548 130 l-12 -6 v12 z" fill="#223344"/>{txt(492,97,'NaBH₄',size=21)}{txt(492,159,'CH₃OH',size=17)}{txt(205,225,'aldehyde',size=18)}{txt(780,225,'primary alcohol',size=18)}</svg>'''
small=reaction();large=reaction(True)
blind=f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 450 230" role="img" aria-label="Unhighlighted large aldehyde for practice"><rect width="450" height="230" fill="white"/>{molecule(True,False,False)}</svg>'
for name,svg in [('simple-reaction',small),('sites-that-matter',large),('find-it-yourself',blind)]:
 (P/(name+'.svg')).write_text(svg)
 doc=fitz.open(stream=svg.encode(),filetype='svg');doc[0].get_pixmap(matrix=fitz.Matrix(1.4,1.4)).save(P/(name+'.png'))
body=f'''
<header><p class="eyebrow">NO FEAR OCHEM · CHAPTER 17 PILOT</p><h1>Find the site.<br>Follow the change.</h1><p class="intro">A small teaching sample for Janice’s review. Start with one clear pattern, then recognise it inside a bigger molecule.</p><p class="tag">Draft teaching sample · not a complete chapter</p></header>
<section><p class="eyebrow">01 · THE REACTION IN ONE FRIENDLY SENTENCE</p><h2>NaBH₄ turns an aldehyde into a primary alcohol.</h2><h3>Goal</h3><p>Find the reacting group and draw its change, even inside a large molecule.</p><h3>What should you notice first?</h3><p>First, find a carbon double-bonded to oxygen and also bonded to H. That end group is an <b>aldehyde</b>.</p>{small}<p><b>Look at what changed:</b> the C=O double bond becomes a C–O single bond. That carbon gains H, and the oxygen gains H. The end group is now CH₂OH.</p><p>A <b>primary alcohol</b> has its OH-bearing carbon attached to one other carbon. Here, that carbon is the CH₂ in CH₂OH.</p><div class="note"><b>Read the arrow:</b> NaBH₄ is sodium borohydride, the reagent that brings about the reduction. CH₃OH is methanol, the solvent shown in this example. Use the conditions printed in your question.</div></section>
<section><p class="eyebrow">02 · SITES THAT MATTER</p><h2>Same change. Bigger molecule.</h2><p>This molecule looks busy. Start at the <b>aldehyde</b>: the carbon with both C=O and a bond to H. NaBH₄ turns that group into a <b>primary alcohol</b>, with CH₂OH at the end.</p>{large}<div class="legend"><span style="color:#1765b0">● Blue carbon: electron-poor</span><span style="color:#c43a40">● Red oxygen: electron-rich</span><span>Grey: unchanged in this reaction</span></div><p><b>Why these colours?</b> Oxygen pulls shared electrons towards itself. This leaves the carbon electron-poor and the oxygen electron-rich. The outline marks the region to inspect; it does not mean charge.</p><p>The rings and the connecting chain stay the same under these conditions. Keep their shape as you draw the product. Work on the highlighted end.</p><p class="small">Original illustrative molecule: 4-(4-cyclohexylphenyl)butanal. This is not a reproduced or verified Smith EOC structure. The grey region is unchanged for this particular reaction; it is not a universal “ignore” label.</p><h3>Your turn: find it without the colours</h3><div class="practice">{blind}<div><p>You have NaBH₄ in CH₃OH.</p><ol><li>Point to the aldehyde.</li><li>Mark the bond that changes.</li><li>Draw the product, keeping the rest of the skeleton.</li></ol><details><summary>Check your thinking</summary><p>The aldehyde is at the far right. Change its C=O to C–OH and add H to that carbon. The end becomes CH₂OH. Both rings and the chain stay intact.</p></details></div></div></section>
<section><p class="eyebrow">03 · NO FEAR PASSAGE + REUSABLE TOOL</p><h2>Give the carbonyl carbon H—or give it carbon.</h2><p>A <b>carbonyl group</b> is C=O: carbon double-bonded to oxygen. In this first pair of reaction families, your decision is what the reagent adds to that carbon.</p><div class="grid"><div class="card"><h3>NaBH₄: add H</h3><p>NaBH₄ turns an aldehyde into a primary alcohol, or a ketone into a secondary alcohol.</p><p>A <b>ketone</b> has its C=O carbon bonded to two carbons. Its product is a <b>secondary alcohol</b>: the OH-bearing carbon remains attached to two carbons.</p><p><b>Carbon count:</b> no new carbon is added.</p></div><div class="card"><h3>A Grignard reagent: add a carbon group</h3><p>A <b>Grignard reagent</b> contains a carbon–magnesium bond, often written R–MgBr. Its carbon group forms a new bond to the C=O carbon. The later water or acid step turns O⁻ into OH.</p><p><b>Carbon count:</b> the incoming group adds carbon to the product.</p></div></div><h3>Tool: decide what goes onto C=O</h3><ol><li><b>Find every C=O.</b> Check what is attached to each carbonyl carbon. An aldehyde has H there; a ketone has carbon groups on both sides.</li><li><b>Read the reagent.</b> Is this the NaBH₄ pattern, or a carbon-adding Grignard reagent?</li><li><b>Check for an interfering group.</b> With a Grignard reagent, an unprotected O–H or N–H can consume reagent by transferring H⁺.</li><li><b>Draw the change and check the carbon count.</b> For the aldehyde/ketone patterns above, C=O becomes C–OH after the appropriate proton-transfer step.</li></ol><div class="note"><b>Keep the boundary visible:</b> a carbonyl attached to O, N, or Cl is a different starting pattern. Do not extend this tool to every C=O. Carboxylic acid derivatives need their own reagent and leaving-group checks.</div><h3>Common trap</h3><p>Do not add a new carbon when using NaBH₄. It adds hydrogen in this pattern. Check the carbon count before and after.</p><h3>Quick check</h3><p>You reduce an aldehyde with NaBH₄. Does the product have more carbon atoms?</p><details><summary>Show the answer</summary><p>No. NaBH₄ adds hydrogen in this reaction. It does not add a carbon group.</p></details></section>
<section><p class="eyebrow">04 · INFO CARD</p><h2>Smith 17.48: check the O–H before building the Grignard reagent.</h2><p><b>What is this testing?</b> Whether another group in the molecule stops your planned reaction.</p><p><b>Look here first:</b> the starting material has an O–H bond as well as a carbon–bromine bond used to make the Grignard reagent.</p><p><b>Why it matters:</b> a Grignard reagent is also a strong base—it can take H⁺ from O–H. That consumes the carbon–magnesium reagent before the planned carbon–carbon bond can form.</p><p><b>Think before drawing:</b> which bond could supply H⁺? What would that do to the carbon–magnesium bond you need?</p><p><b>Your next decision:</b> how could you stop that interfering reaction temporarily and still restore the OH at the end?</p><p><b>Ochem II point:</b> inspect the whole molecule once before deciding which region you can leave alone.</p><p><b>Returns later in:</b> multistep synthesis and choosing protecting groups.</p><p class="small">Question task and explanation checked against extracted textbook/solution text. The complete reaction sequence and target structure still require visual inspection.</p></section>
<section><p class="eyebrow">05 · EOC ANSWER-FACT SAMPLE</p><h2>What does the student need to know?</h2><p>These are short teaching explanations, not complete structural answers. No missing textbook drawing has been reconstructed from guesswork.</p><table><thead><tr><th>Source</th><th>Friendly answer fact</th><th>Check status</th></tr></thead><tbody>
<tr><td>Smith 17.39(a)</td><td>NaBH₄ turns this ketone into a secondary alcohol. This starting ketone is achiral—it has no handedness. Reaction from either face gives an equal mixture of two mirror-image alcohols.</td><td>Task and named substrate readable. Full solution drawing pending.</td></tr>
<tr><td>Smith 17.48</td><td>The unprotected OH consumes the Grignard reagent. Protect the OH first, carry out the carbon-adding steps, then remove the protection.</td><td>Core explanation checked in solution text. Complete sequence pending.</td></tr>
<tr><td>Klein 12.38(a)</td><td>Work backwards from the primary alcohol: change CH₂OH back into an aldehyde. Keep the carbon skeleton the same.</td><td>Solution text identifies an aldehyde. Exact skeleton pending.</td></tr>
<tr><td>Klein 12.38(b), (c)</td><td>Work backwards from the secondary alcohol: change CH–OH back into C=O. Keep the two carbon groups attached to that carbon.</td><td>Solution text identifies ketones. Exact skeletons pending.</td></tr></tbody></table><p><b>The transfer pattern:</b> the forward question asks what the reagent makes. Klein’s reverse question asks what starting material could make the alcohol. The student uses the same local bond change in opposite directions.</p></section>
<section class="audit"><p class="eyebrow">SOURCE CHECK · FOR JANICE</p><h2>What is verified—and what is still open?</h2><ul><li><b>Smith textbook:</b> sixth edition confirmed in title/copyright text. Chapter 17 starts at printed page 780; chapter 18 starts at 833. Chapter 17 EOCs begin on page 825.</li><li><b>Smith solutions:</b> sixth edition confirmed. Chapter 17 occupies labelled pages 17–1 through 17–30. Matching numbering and topic checked for the sample; all diagrams are not yet checked.</li><li><b>Klein textbook and solutions:</b> fourth edition confirmed in the book text and manual title.</li><li><b>Klein match:</b> chapter 12, Alcohols and Phenols, is the best starting companion for reduction, Grignard addition, and OH protection. Chapters 13, 19, and 20 provide additional relevant topics. Exact question mappings remain to be completed.</li><li><b>Visual access:</b> the Drive tool returned PDF file references but no local PDF bytes. Extracted text omits many structures. The drawings above are original teaching examples; they are not evidence that source diagrams have passed inspection.</li><li><b>Coverage:</b> this is a bounded pilot. It does not establish that the chapter toolkit answers every EOC.</li></ul><h3>Review just three things</h3><p>Is the tutor voice right? Does the grey skeleton make the reaction site easier to find? Is the amount of explanation right before we scale up?</p><p class="small">Source links: <a href="https://drive.google.com/file/d/1N_V604VbKr3R0pNGAl97korEBk570yeC/view">Smith textbook</a> · <a href="https://drive.google.com/file/d/1UVD9DpDm1twW1OhICUjvAA72LhaAgf6v/view">Smith solutions</a> · <a href="https://drive.google.com/file/d/10DHuWuXxxPXaVsJQEEC6SdKPtkfAajHN/view">Klein textbook</a> · <a href="https://drive.google.com/file/d/1HYhG8rARCc0QDtJj2N15oU3_bJEXbHZi/view">Klein solutions</a></p></section>'''
css='''*{box-sizing:border-box}body{margin:0;background:#f1f4f3;color:#233342;font:18px/1.65 Arial,sans-serif}main{max-width:1080px;margin:auto;padding:40px 24px}header{background:#133e3b;color:white;padding:45px;border-radius:18px;margin-bottom:25px}h1{font-size:54px;line-height:1.08;margin:18px 0}h2{font-size:29px;line-height:1.25;margin:10px 0 20px}h3{font-size:21px}p{margin:12px 0}.eyebrow{font-size:12px;font-weight:bold;letter-spacing:1.6px;color:#178477}header .eyebrow{color:#a9d8cf}.intro{max-width:740px}.tag{font-size:13px;color:#c6dfd9}section{background:white;border:1px solid #dbe3df;border-radius:16px;padding:34px;margin-bottom:25px}svg{width:100%;height:auto;margin:12px 0}.note{background:#eef6f3;border-left:4px solid #178477;padding:16px 20px;margin:22px 0}.small{font-size:13px;color:#617080}.legend{display:flex;gap:25px;flex-wrap:wrap;font-size:14px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.card{background:#f7f9f8;border:1px solid #dfe5e1;border-radius:12px;padding:20px}.practice{display:grid;grid-template-columns:1fr 1fr;gap:20px;align-items:center}li{margin-bottom:10px}details{padding:12px 15px;background:#eef6f3;border-radius:8px;margin:14px 0}summary{cursor:pointer;font-weight:bold}table{border-collapse:collapse;width:100%;font-size:15px}th,td{text-align:left;vertical-align:top;border-bottom:1px solid #dce4df;padding:14px}th{background:#eef6f3}.audit{font-size:15px}a{color:#176e65}@media(max-width:650px){main{padding:15px}section,header{padding:22px}.grid,.practice{grid-template-columns:1fr}h1{font-size:38px}h2{font-size:24px}table{font-size:12px}td,th{padding:6px}}@media print{body{background:white;font-size:12pt}main{padding:0}section{break-inside:avoid}header{color:#133e3b;background:white}details{display:block}details>*{display:block}h1{font-size:34pt}}'''
(P/'chapter-17-teaching-sample.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Chapter 17 · No Fear teaching sample</title><style>'+css+'</style><main>'+body+'</main></html>')
# Audit text without HTML markup.
from html.parser import HTMLParser
class Text(HTMLParser):
 def __init__(self):super().__init__();self.s=[]
 def handle_starttag(self,tag,attrs):
  if tag in ['h1','h2','h3']: self.s.append('\n\n## ')
 def handle_endtag(self,tag):
  if tag in ['p','li','h1','h2','h3','tr','div']:self.s.append('\n\n')
 def handle_data(self,d):self.s.append(d)
t=Text();t.feed(body);(P/'teaching-text.md').write_text(''.join(t.s))
print('Created HTML teaching sample and three exact vector illustrations.')
