/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as QuestionBankRouteImport } from './routes/question-bank'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuickSheetsIndexRouteImport } from './routes/quick-sheets.index'
import { Route as QuickSheetsSheetIdRouteImport } from './routes/quick-sheets.$sheetId'
import { Route as QuestionQuestionIdRouteImport } from './routes/question.$questionId'
import { Route as SprintChapterIdRouteImport } from './routes/sprint.$chapterId'
import { Route as ChapterChapterIdIndexRouteImport } from './routes/chapter.$chapterId.index'
import { Route as ChapterChapterIdMapRouteImport } from './routes/chapter.$chapterId.map'

const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionBankRoute = QuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickSheetsIndexRoute = QuickSheetsIndexRouteImport.update({
  id: '/quick-sheets/',
  path: '/quick-sheets/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickSheetsSheetIdRoute = QuickSheetsSheetIdRouteImport.update({
  id: '/quick-sheets/$sheetId',
  path: '/quick-sheets/$sheetId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionQuestionIdRoute = QuestionQuestionIdRouteImport.update({
  id: '/question/$questionId',
  path: '/question/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintChapterIdRoute = SprintChapterIdRouteImport.update({
  id: '/sprint/$chapterId',
  path: '/sprint/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterChapterIdIndexRoute = ChapterChapterIdIndexRouteImport.update({
  id: '/chapter/$chapterId/',
  path: '/chapter/$chapterId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterChapterIdMapRoute = ChapterChapterIdMapRouteImport.update({
  id: '/chapter/$chapterId/map',
  path: '/chapter/$chapterId/map',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/question-bank': typeof QuestionBankRoute
  '/review': typeof ReviewRoute
  '/question/$questionId': typeof QuestionQuestionIdRoute
  '/sprint/$chapterId': typeof SprintChapterIdRoute
  '/quick-sheets/$sheetId': typeof QuickSheetsSheetIdRoute
  '/quick-sheets/': typeof QuickSheetsIndexRoute
  '/chapter/$chapterId/map': typeof ChapterChapterIdMapRoute
  '/chapter/$chapterId/': typeof ChapterChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/question-bank': typeof QuestionBankRoute
  '/review': typeof ReviewRoute
  '/question/$questionId': typeof QuestionQuestionIdRoute
  '/sprint/$chapterId': typeof SprintChapterIdRoute
  '/quick-sheets/$sheetId': typeof QuickSheetsSheetIdRoute
  '/quick-sheets': typeof QuickSheetsIndexRoute
  '/chapter/$chapterId/map': typeof ChapterChapterIdMapRoute
  '/chapter/$chapterId': typeof ChapterChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/question-bank': typeof QuestionBankRoute
  '/review': typeof ReviewRoute
  '/question/$questionId': typeof QuestionQuestionIdRoute
  '/sprint/$chapterId': typeof SprintChapterIdRoute
  '/quick-sheets/$sheetId': typeof QuickSheetsSheetIdRoute
  '/quick-sheets/': typeof QuickSheetsIndexRoute
  '/chapter/$chapterId/map': typeof ChapterChapterIdMapRoute
  '/chapter/$chapterId/': typeof ChapterChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/progress'
    | '/question-bank'
    | '/review'
    | '/question/$questionId'
    | '/sprint/$chapterId'
    | '/quick-sheets/$sheetId'
    | '/quick-sheets/'
    | '/chapter/$chapterId/map'
    | '/chapter/$chapterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/progress'
    | '/question-bank'
    | '/review'
    | '/question/$questionId'
    | '/sprint/$chapterId'
    | '/quick-sheets/$sheetId'
    | '/quick-sheets'
    | '/chapter/$chapterId/map'
    | '/chapter/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/progress'
    | '/question-bank'
    | '/review'
    | '/question/$questionId'
    | '/sprint/$chapterId'
    | '/quick-sheets/$sheetId'
    | '/quick-sheets/'
    | '/chapter/$chapterId/map'
    | '/chapter/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgressRoute: typeof ProgressRoute
  QuestionBankRoute: typeof QuestionBankRoute
  ReviewRoute: typeof ReviewRoute
  QuestionQuestionIdRoute: typeof QuestionQuestionIdRoute
  SprintChapterIdRoute: typeof SprintChapterIdRoute
  QuickSheetsSheetIdRoute: typeof QuickSheetsSheetIdRoute
  QuickSheetsIndexRoute: typeof QuickSheetsIndexRoute
  ChapterChapterIdMapRoute: typeof ChapterChapterIdMapRoute
  ChapterChapterIdIndexRoute: typeof ChapterChapterIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-bank': {
      id: '/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof QuestionBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-sheets/': {
      id: '/quick-sheets/'
      path: '/quick-sheets'
      fullPath: '/quick-sheets/'
      preLoaderRoute: typeof QuickSheetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-sheets/$sheetId': {
      id: '/quick-sheets/$sheetId'
      path: '/quick-sheets/$sheetId'
      fullPath: '/quick-sheets/$sheetId'
      preLoaderRoute: typeof QuickSheetsSheetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question/$questionId': {
      id: '/question/$questionId'
      path: '/question/$questionId'
      fullPath: '/question/$questionId'
      preLoaderRoute: typeof QuestionQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprint/$chapterId': {
      id: '/sprint/$chapterId'
      path: '/sprint/$chapterId'
      fullPath: '/sprint/$chapterId'
      preLoaderRoute: typeof SprintChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/$chapterId/': {
      id: '/chapter/$chapterId/'
      path: '/chapter/$chapterId'
      fullPath: '/chapter/$chapterId/'
      preLoaderRoute: typeof ChapterChapterIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/$chapterId/map': {
      id: '/chapter/$chapterId/map'
      path: '/chapter/$chapterId/map'
      fullPath: '/chapter/$chapterId/map'
      preLoaderRoute: typeof ChapterChapterIdMapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgressRoute: ProgressRoute,
  QuestionBankRoute: QuestionBankRoute,
  ReviewRoute: ReviewRoute,
  QuestionQuestionIdRoute: QuestionQuestionIdRoute,
  SprintChapterIdRoute: SprintChapterIdRoute,
  QuickSheetsSheetIdRoute: QuickSheetsSheetIdRoute,
  QuickSheetsIndexRoute: QuickSheetsIndexRoute,
  ChapterChapterIdMapRoute: ChapterChapterIdMapRoute,
  ChapterChapterIdIndexRoute: ChapterChapterIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
